"""initial_schema

Revision ID: 04dd1eabaa39
Revises: 
Create Date: 2026-06-05 12:58:26.729515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04dd1eabaa39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('model_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_tag', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_profile_keycloak_sub'), 'user_profile', ['keycloak_sub'], unique=True)
    op.create_table('calibration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('calibrated_by_id', sa.UUID(), nullable=False),
    sa.Column('left_camera_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('right_camera_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('left_dist_coeffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('right_dist_coeffs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rotation_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('translation_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_mm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('image_width_px', sa.Integer(), nullable=False),
    sa.Column('image_height_px', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calibrated_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_device_id'), 'calibration', ['device_id'], unique=False)
    op.create_table('quarry_user_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quarry_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarry_user_access_quarry_id'), 'quarry_user_access', ['quarry_id'], unique=False)
    op.create_index(op.f('ix_quarry_user_access_user_id'), 'quarry_user_access', ['user_id'], unique=False)
    op.create_index('uq_quarry_user_active', 'quarry_user_access', ['user_id', 'quarry_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('site_section',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quarry_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('block_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_section_quarry_id'), 'site_section', ['quarry_id'], unique=False)
    op.create_table('blast_passport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_section_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'SUPERSEDED', name='passport_status'), nullable=False),
    sa.Column('blast_date_planned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('explosive_type', sa.String(length=255), nullable=True),
    sa.Column('total_explosive_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('number_of_holes', sa.Integer(), nullable=True),
    sa.Column('hole_diameter_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hole_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('burden_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('spacing_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('stemming_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('target_p80_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['site_section_id'], ['site_section.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['blast_passport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blast_passport_site_section_id'), 'blast_passport', ['site_section_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('passport_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['blast_passport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_passport_id'), 'audit_log', ['passport_id'], unique=False)
    op.create_table('blast_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passport_id', sa.UUID(), nullable=False),
    sa.Column('executed_by_id', sa.UUID(), nullable=False),
    sa.Column('blast_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_explosive_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weather_conditions', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['blast_passport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport_id')
    )
    op.create_table('capture_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blast_event_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('calibration_id', sa.UUID(), nullable=False),
    sa.Column('captured_by_id', sa.UUID(), nullable=False),
    sa.Column('capture_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blast_event_id'], ['blast_event.id'], ),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibration.id'], ),
    sa.ForeignKeyConstraint(['captured_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_session_blast_event_id'), 'capture_session', ['blast_event_id'], unique=False)
    op.create_table('analysis_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_session_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_job_capture_session_id'), 'analysis_job', ['capture_session_id'], unique=False)
    op.create_index(op.f('ix_analysis_job_celery_task_id'), 'analysis_job', ['celery_task_id'], unique=False)
    op.create_table('analysis_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('p10_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('p50_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('p80_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rosin_rammler_n', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rosin_rammler_xc', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('uniformity_index', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('oversize_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fines_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('total_particles_counted', sa.Integer(), nullable=True),
    sa.Column('total_volume_m3', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.Column('size_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_session_id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.Enum('LEFT_FRAME', 'RIGHT_FRAME', 'DEPTH_MAP', 'POINT_CLOUD', 'MASK', 'PARTICLE_LIST', 'REPORT_FILE', name='artifact_type'), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_job.id'], ),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_analysis_job_id'), 'artifact', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_artifact_capture_session_id'), 'artifact', ['capture_session_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_result.id'], ),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REQUIRES_HUMAN_REVIEW', 'DRAFT', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='recommendation_status'), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('parameter_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_report_id'), 'recommendation', ['report_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_recommendation_id'), 'comment', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_recommendation_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_recommendation_report_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_table('report')
    op.drop_index(op.f('ix_artifact_capture_session_id'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_analysis_job_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_table('analysis_result')
    op.drop_index(op.f('ix_analysis_job_celery_task_id'), table_name='analysis_job')
    op.drop_index(op.f('ix_analysis_job_capture_session_id'), table_name='analysis_job')
    op.drop_table('analysis_job')
    op.drop_index(op.f('ix_capture_session_blast_event_id'), table_name='capture_session')
    op.drop_table('capture_session')
    op.drop_table('blast_event')
    op.drop_index(op.f('ix_audit_log_passport_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_blast_passport_site_section_id'), table_name='blast_passport')
    op.drop_table('blast_passport')
    op.drop_index(op.f('ix_site_section_quarry_id'), table_name='site_section')
    op.drop_table('site_section')
    op.drop_index('uq_quarry_user_active', table_name='quarry_user_access', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_quarry_user_access_user_id'), table_name='quarry_user_access')
    op.drop_index(op.f('ix_quarry_user_access_quarry_id'), table_name='quarry_user_access')
    op.drop_table('quarry_user_access')
    op.drop_index(op.f('ix_calibration_device_id'), table_name='calibration')
    op.drop_table('calibration')
    op.drop_index(op.f('ix_user_profile_keycloak_sub'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_table('role')
    op.drop_table('quarry')
    op.drop_table('model_version')
    op.drop_table('device')
    # ### end Alembic commands ###
