"""add_index_analysis_job_model_version_id

Revision ID: 6929bdaa526b
Revises: 0002
Create Date: 2026-06-06 04:20:09.372137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6929bdaa526b'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_job_model_version_id'), 'analysis_job', ['model_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_job_model_version_id'), table_name='analysis_job')
    # ### end Alembic commands ###
