"""analysis_job frame_index

Revision ID: 75bb00d854b1
Revises: 6929bdaa526b
Create Date: 2026-06-10 20:43:38.579673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bb00d854b1'
down_revision: Union[str, None] = '6929bdaa526b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_job', sa.Column('frame_index', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_job', 'frame_index')
    # ### end Alembic commands ###
